import enum


class ViewsList(enum.Enum):
    START = 0
    LOGIN = 1
    REGISTER = 2
    CONFIGURE = 3
    DASHBOARD = 5
    ADD_RETURN = 6
    IMPORT = 7
    EXPORT = 8
    RECORD_LIST = 9
    ADD_ACCOUNT = 10
    ADD_INVOICE = 11
    ADD_PROJECT = 12
    ADD_TRANSACTION = 13
    ADD_VENDOR = 14
    ADD_PERMISSION = 15
    DETAILED_ACCOUNT = 16
    DETAILED_INVOICE = 17
    DETAILED_PROJECT = 18
    DETAILED_TRANSACTION = 19
    DETAILED_VENDOR = 20
    GRAPH = 21
    GENERATE_INVOICE = 22



